<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyFirmowaBundleEntityZamowienieProxy extends \My\FirmowaBundle\Entity\Zamowienie implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setDataPrzyjecia($dataPrzyjecia)
    {
        $this->__load();
        return parent::setDataPrzyjecia($dataPrzyjecia);
    }

    public function getDataPrzyjecia()
    {
        $this->__load();
        return parent::getDataPrzyjecia();
    }

    public function setDataOdbioru($dataOdbioru)
    {
        $this->__load();
        return parent::setDataOdbioru($dataOdbioru);
    }

    public function getDataOdbioru()
    {
        $this->__load();
        return parent::getDataOdbioru();
    }

    public function setUsterka($usterka)
    {
        $this->__load();
        return parent::setUsterka($usterka);
    }

    public function getUsterka()
    {
        $this->__load();
        return parent::getUsterka();
    }

    public function setNumerZamowienia($numerZamowienia)
    {
        $this->__load();
        return parent::setNumerZamowienia($numerZamowienia);
    }

    public function getNumerZamowienia()
    {
        $this->__load();
        return parent::getNumerZamowienia();
    }

    public function getKlienci()
    {
        $this->__load();
        return parent::getKlienci();
    }

    public function setKlienci($klienci)
    {
        $this->__load();
        return parent::setKlienci($klienci);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'data_przyjecia', 'data_odbioru', 'Usterka', 'numer_zamowienia', 'klienci');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}